---
collections:
  - name: amazon.aws
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.windows
  - name: arista.eos
  - name: awx.awx
  - name: azure.azcollection
  - name: check_point.mgmt
  - name: chocolatey.chocolatey
  - name: cisco.aci
  - name: cisco.asa
  - name: cisco.dnac
  - name: cisco.intersight
  - name: cisco.ios
  - name: cisco.iosxr
  - name: cisco.ise
  - name: cisco.meraki
  - name: cisco.mso
  - name: cisco.nxos
  - name: cisco.ucs
  - name: cloud.common
  - name: cloudscale_ch.cloud
  - name: community.aws
  - name: community.ciscosmb
  - name: community.crypto
  - name: community.digitalocean
  - name: community.dns
  - name: community.docker
  - name: community.general
  - name: community.grafana
  - name: community.hashi_vault
  - name: community.hrobot
  - name: community.library_inventory_filtering_v1
  - name: community.libvirt
  - name: community.mongodb
  - name: community.mysql
  - name: community.network
  - name: community.okd
  - name: community.postgresql
  - name: community.proxysql
  - name: community.rabbitmq
  - name: community.routeros
  - name: community.sap_libs
  - name: community.sops
  - name: community.vmware
  - name: community.windows
  - name: community.zabbix
  - name: containers.podman
  - name: cyberark.conjur
  - name: cyberark.pas
  - name: dellemc.enterprise_sonic
  - name: dellemc.openmanage
  - name: dellemc.powerflex
  - name: dellemc.unity
  - name: f5networks.f5_modules
  - name: fortinet.fortimanager
  - name: fortinet.fortios
  - name: google.cloud
  - name: grafana.grafana
  - name: hetzner.hcloud
  - name: ibm.qradar
  - name: ibm.spectrum_virtualize
  - name: ibm.storage_virtualize
  - name: ieisystem.inmanage
  - name: infinidat.infinibox
  - name: infoblox.nios_modules
  - name: inspur.ispim
  - name: junipernetworks.junos
  - name: kaytus.ksmanage
  - name: kubernetes.core
  - name: kubevirt.core
  - name: lowlydba.sqlserver
  - name: microsoft.ad
  - name: netapp.cloudmanager
  - name: netapp.ontap
  - name: netapp.storagegrid
  - name: netapp_eseries.santricity
  - name: netbox.netbox
  - name: ngine_io.cloudstack
  - name: openstack.cloud
  - name: ovirt.ovirt
  - name: purestorage.flasharray
  - name: purestorage.flashblade
  - name: sensu.sensu_go
  - name: splunk.es
  - name: telekom_mms.icinga_director
  - name: theforeman.foreman
  - name: vmware.vmware
  - name: vmware.vmware_rest
  - name: vultr.cloud
  - name: vyos.vyos
  - name: wti.remote